### ISSUE TITLE
Add Local Development Setup Instructions to Documentation

### ISSUE THREAD

**Issue by Anonymous961** [brisa-build/brisa#535]
The current documentation does not include steps for setting up the project for local development. Adding these steps would help contributors and developers get started quickly. Could we include a section that covers installation, dependencies, and running the project locally?

**Comment by aralroca** [comment]
You only need to run `bun create brisa` after install Bun. If you want a manual process is already detailed:

<img width="728" alt="Screenshot 2024-10-09 at 12 26 41" src="https://github.com/user-attachments/assets/d921ccd5-6daa-462f-8a97-3354f03fd8f2">

if there are things that are not clear it is good to comment them here and see how we can improve them.

The link is this one: https://brisa.build/getting-started/quick-start

thanks @Anonymous961

**Comment by aralroca** [comment]
@Anonymous961 feel free to contribute editing the points that can be improved, all contributions are very welcomed

**Comment by chankruze** [comment]
@aralroca  I think @Anonymous961 is talking about setup instructions in [CONTRIBUTING.md](https://github.com/brisa-build/brisa/blob/canary/CONTRIBUTING.md) maybe 😐

**Comment by Anonymous961** [comment]
@chankruze, you're right! I was referring to local development instructions specifically for contributors. It would be helpful to have a guide on how to clone the repo, set up the environment, and begin local development. Additionally, it would be great to clarify the process for code reviews and who contributors should reach out to when seeking feedback.

**Comment by aralroca** [comment]
Ah ok! Got it! Totally agree, this can be improved a lot. Probably related to https://github.com/brisa-build/brisa/issues/533#issuecomment-2401549366 too

**Comment by aralroca** [comment]
@Anonymous961  @chankruze  There are tests, such as Node tests among others, that need to have the bun run build (maybe looking to the GH action can help).

Surely it can be explained better, but I leave here what is really necessary:

- `git clone git@github.com:brisa-build/brisa.git`
- `bun install`
- `bun run build:all`

And then to work:

- create a test file or use an existing one and put: `bun run test path/to/file.test.ts --watch` and modify the related file.
- You can symlink Brisa in a project (`bun create brisa`) and be able to test what is being developed using the symlink.

Feel free to contribute by improving this file by explaining it better or adding some detail to help the beginner. It is likely that since you are not familiar with it, you can clarify any initial doubts you may have had.

Apart from this, there are some tests (9 approx from +3k) that in the new versions of Bun have stopped working when running `bun run test`, although they pass fine when run in isolation running only the test suite. I would like to finish fixing this problem to make it more comfortable to contribute.
