### ISSUE TITLE
Form action should work without JavaScript

### ISSUE THREAD

**Issue by aralroca** [brisa-build/brisa#595]
After the change of the indicator:

https://github.com/brisa-build/brisa/pull/585

but the indicator usage in the Brisa core introduces an issue, since it looks at the header of x-action to know if it is an action. This header is not being set in case of not having JavaScript, and the form actions should still work.

**Comment by lattaai2** [comment]
Hello, I tried to fix the issue

This is what I did:
I have identified the issue and implemented a solution to ensure that form actions work correctly even when JavaScript is disabled. The problem was in the `isAnAction` function, which was checking for properties that are only available when JavaScript is enabled. I've updated this function to use a more reliable method of identifying actions.

I also created pull request: https://github.com/brisa-build/brisa/pull/596


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by aralroca** [comment]
@lattaai2 This is-an-action is for attribute detection, since we support action propagation in rendering. But it has nothing to do with the detection of processing a POST action request from a form. Thanks anyway for trying to fix it. This was working fine before, behind this [PR](https://github.com/brisa-build/brisa/pull/585) the bug was added. The best thing to do is to fix the getIndicator. In fact I had assigned me the issue because I have clear the fix part.
