### ISSUE TITLE
`onMount` called before the WC is on the DOM (during SPA navigation)

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#611]
**Describe the bug**
When using `onMount` and `setAttribute` to add some extra attribute to the WC, is lost during navigation because the `onMount` execution is before the diffing algorithm adds the WC to the DOM, then loses this extra attribute.

**To Reproduce**
Try to edit an element inside onMount, this will have no effect on the DOM.

**Expected behavior**
Edit an element on onMount should be reflected to the DOM.

**Comment by aralroca** [comment]
I will try to generate the failing test. I think the problem relates to the asynchrony of doing the `mount`, not the `onMount` method. All `onMount` methods are executed after running the `mount`, but the `mount` has an `await` here:

https://github.com/brisa-build/brisa/blob/61f18d2592bc8313108ea9f4ff13dfe118425d14/packages/brisa/src/utils/brisa-element/index.ts#L244

Meanwhile in these `mount` calls no `await` is made.

https://github.com/brisa-build/brisa/blob/61f18d2592bc8313108ea9f4ff13dfe118425d14/packages/brisa/src/utils/brisa-element/index.ts#L315-L321

**Comment by aralroca** [comment]
## Detected bug annotations

**_after debugging... I got the root of the problem...!_**

I have seen the problem that is happening. Something I didn't expect, but it works like this... The web component is mounted before the component is visible in the DOM.

The reason, that in the diffing algorithm, we are parsing the chunks that are arriving in streaming using:

```ts
 const doc = document.implementation.createHTMLDocument();
```

[_🔗 Code_](https://github.com/aralroca/diff-dom-streaming/blob/0169dc1c9315099f340f7d60599e9fecf201eaca/src/index.ts#L220)

> [!NOTE]
>
> All this "magic trick to parse HTML nodes" is better explained in this [Chrome video](https://www.youtube.com/watch?v=LLRig4s1_yA) by @jakearchibald

We use the [createHTMLDocument](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument) to parse the chunks into strings with a browser tool in order to have the real nodes in a separate DOM and to be able to compare them later with the nodes of the current DOM using the diffing algorithm and then use them on the real DOM.

I never thought that by parsing in createHTMLDocument the web components registered with `customerElements.define()` would be mounted here inside, but it seems to be true and it works like this.


I see that when building the node calling the walker is mounting the Web Component:

```ts
let newNode = await walker[FIRST_CHILD](newParent);
```

[_🔗 Code_](https://github.com/aralroca/diff-dom-streaming/blob/0169dc1c9315099f340f7d60599e9fecf201eaca/src/index.ts#L133)

And then, later, it's added to the DOM here, losing this internal modification via `setAttribute` inside the Web Component.

```ts
oldParent.insertBefore(insertedNode!, checkOld!),
```

[_🔗 Code_](https://github.com/aralroca/diff-dom-streaming/blob/0169dc1c9315099f340f7d60599e9fecf201eaca/src/index.ts#L176)

This would also explain other issues such as the double re-rendering https://github.com/brisa-build/brisa/issues/550 that sometimes happens with some web components when diffing when browsing. It is probable that the double re-render happens because we are doing a clone and the render is done in the [createHTMLDocument](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument) and finally another one in the real DOM.

## How to solve this?

Ideally, the `document.implementation.createHTMLDocument()` should not use the defined WCs and should only be mounted in the actual DOM. How feasible is it to do this? No idea. Maybe @jakearchibald can give us some advice here.

The reason why we are using `document.implementation.createHTMLDocument()` is so that in the MPA navigation it acts as SPA after comparing the parsed nodes from chunks that arrive in streaming with the current nodes, the diffing algorithm it updates only the parts that have changed, thanks to the [Navigation API](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_API). 

It is the only native tool available that I know of to be able to do this. However, we want to avoid mounting the WC before it is visible in the actual DOM, and only mount it at this instant....

**Comment by aralroca** [comment]
I need to fit some more pieces to understand the problem. Maybe I am wrong with the explanation above. After debugging the problem it looks like everything I said above. However, after adding a `console.log` inside the WC render, no log is done doing this:

![Screenshot 2024-11-08 at 23 55 37](https://github.com/user-attachments/assets/ffdcddb6-377b-4044-b751-0ce2e7676f6c)

and the custom element is defined 🤔 No log... No render, no mount. All looks correct... I don't understand now.

**Comment by aralroca** [comment]
[Here](https://github.com/cure53/DOMPurify/issues/47) they talk about this error and that one solution is to change it to:

```diff
- const doc = document.implementation.createHTMLDocument();
+const doc = document.createElement('template').content.ownerDocument;
```

It is an option to try, although I don't know if the magic trick to parse in streaming will be feasable, we will have to try it.

**Comment by aralroca** [comment]
> [Here](https://github.com/cure53/DOMPurify/issues/47) they talk about this error and that one solution is to change it to:
> 
> ```diff
> - const doc = document.implementation.createHTMLDocument();
> +const doc = document.createElement('template').content.ownerDocument;
> ```
> 
> It is an option to try, although I don't know if the magic trick to parse in streaming will be feasable, we will have to try it.
 
 
 I've tried, the good part is that the streaming and diffing is still working fine. The bad part is that it does not fix the bug. We must be missing something.... I have also tried with:

```ts
document.createElement('template').content.ownerDocument.implementation.createHTMLDocument()
```

and

```ts
const parser = new DOMParser(); 
const doc = parser.parseFromString('', 'text/html');
```

But the same thing... We are probably missing something and it could be a different thing... 🤔

**Comment by aralroca** [comment]
**I WAS WRONG!!!** It does exist in the DOM at the time of running the debugger, it looked like it didn't because I had not yet rendered the shadowRoot 😅 I see that after doing mount, this is executed, which is the cause:

```ts
 if (!newAttribute) oldAttributes.removeNamedItemNS(namespace, name);
```

https://github.com/aralroca/diff-dom-streaming/blob/0169dc1c9315099f340f7d60599e9fecf201eaca/src/index.ts#L99

So: It's creating the element and then updating the attributes... Tomorrow I'm going to continue investigating...

**Comment by aralroca** [comment]
@AlbertSabate I did the fix on the diffing algorithm:

https://github.com/aralroca/diff-dom-streaming/pull/18

I realized that there were 2 steps. An insert and then an unnecessary update. In this case the update did a setAttribute only, but probably this second update in other cases is the cause of the double re-rerender reported here https://github.com/brisa-build/brisa/issues/550
