### ISSUE TITLE
Navigate on server action does not read i18n info

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#622]
**Describe the bug**
When using a navigate on a server actions seems to navigate without considering i18n. When having i18n enabled.

Example:

navigate('/admin') navigates to /admin instead of /en/admin

**Comment by aralroca** [comment]
Can you check the `req.finalURL`? We check the i18n here:

https://github.com/brisa-build/brisa/blob/1acd7798d1b61752f464dab89bbffb389be32a23/packages/brisa/src/utils/get-locale-from-request/index.ts#L6-L7

**Comment by AlbertSabate** [comment]
<img width="463" alt="local" src="https://github.com/user-attachments/assets/75235964-198a-462c-9c8a-b7dfea882635">
<img width="607" alt="Screenshot 2024-11-10 at 4 55 10 PM" src="https://github.com/user-attachments/assets/859265f5-ca67-4aae-817f-fcacfc160e57">


The value after the request is request.finalURL

**Comment by aralroca** [comment]
On the server actions build, is importing all the code of the `navigate` import, including the "constants", that are different from after the standalone build (server.js file). That's wrong. The incorrect constants does not have the I18N_CONFIG because does not found the `i18n.js` file there.

<img width="854" alt="Screenshot 2024-11-10 at 23 15 21" src="https://github.com/user-attachments/assets/26a56ba0-240b-4bdf-acb8-4f066b7d050e">

**Comment by AlbertSabate** [comment]
v0.1.5-canary.4 fixes this issue.
